# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Left board, always the same
  - board: nice_nano_v2
    shield: charybdis_left

  # standalone right
  - board: nice_nano_v2
    shield: charybdis_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  
  # peripheral right board
  - board: nice_nano_v2
    shield: charybdis_right_peripheral

  # dongle
  - board: nice_nano_v2
    shield: charybdis_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: charybdis_central_dongle_oled

  # settings reset
  - board: nice_nano_v2
    shield: settings_reset
